const items = [
	{ item: 'Bandages', cost: 1 },
	{ item: 'Lantern', cost: 3 },
	{ item: 'Torch', cost: 1 },
	{ item: 'Backpack', cost: 1 },
	{ item: 'Potion', cost: 6 },
	{ item: 'Ammo', cost: 1 },
	{ item: 'Light Armor', cost: 2 },
	{ item: 'Medium Armor', cost: 10 },
	{ item: 'Heavy Armor', cost: 20 },
	{ item: 'Helm', cost: 5 },
	{ item: 'Shield', cost: 2 },
	{ item: 'One Handed Makeshift Weapon', cost: 0 },
	{ item: 'Staff', cost: 1 },
	{ item: 'Shortsword', cost: 2 },
	{ item: 'Dagger', cost: 1 },
	{ item: 'Warhammer', cost: 4 },
	{ item: 'Sword', cost: 4 },
	{ item: 'Rapier', cost: 4 },
	{ item: 'Fists', cost: 0 },
	{ item: 'Hand Axe', cost: 3 },
	{ item: 'Ulfberht Sword', cost: 5 },
	{ item: 'Morning Star', cost: 7 },
	{ item: "Horseman's Pick", cost: 4 },
	{ item: 'Flail', cost: 5 },
	{ item: 'Two Handed Makeshift Weapon', cost: 0 },
	{ item: 'Bow', cost: 5 },
	{ item: 'Crossbow', cost: 8 },
	{ item: 'Bastard Sword', cost: 10 },
	{ item: 'Great Axe', cost: 10 },
	{ item: 'Glaive', cost: 8 },
	{ item: 'Spear', cost: 8 }
];

export default items;
